backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "pages"
    label: "Pages"
    files:
    # the home page
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Banner", name: banner, widget: object, fields: [
              {label: "Banner Image", name: "image", widget: "image"}]}
          - {label: Hero Image, name: image, widget: image}
          #socials come here...
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "First Paragraph", name: "first-text", widget: "text"},
              {label: "First Paragraph", name: "second-text", widget: "text"},
              {label: "Second Paragraph", name: "third-text", widget: "text"}]}
          - {label: "Songs", name: songs, widget: object, fields: [
              {label: "Songs Heading", name: "heading", widget: "text"},
              {label: "First Song", name: "first-song", widget: "file"},
              {label: "Second Song", name: "second-song", widget: "file"},
              {label: "Third Song", name: "third-song", widget: "file"},
              {label: "Fourth Song", name: "fourth-song", widget: "file"}]}
          - {label: "Footer", name: footer, widget: object, fields: [
              {label: "Footer Image", name: "image", widget: "image"}]}