backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "pages"
    label: "Pages"
    files:
    # the home page
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Banner", name: banner, widget: object, fields: [
              {label: "Banner Image", name: "image", widget: "image"}]}
          - {label: Hero Image, name: image, widget: image}
          #socials come here...
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "First Paragraph", name: "firstText", widget: "text"},
              {label: "Second Paragraph", name: "secondText", widget: "text"}]}
          - {label: "Spotify", name: spotify, widget: object, fields: [
              {label: "Spotify Song", name: "firstSong", widget: "file"}]}
          - {label: "Footer", name: footer, widget: object, fields: [
              {label: "Footer Image", name: "image", widget: "image"}]}