backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "pages"
    label: "Pages"
    files:
    # the home page
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Banner", name: banner, widget: object, fields: [
              {label: "Banner Image", name: "image", widget: "image"}]}
          - {label: Hero Image, name: image, widget: image}
          #socials come here...
          - {label: "Socials", name: socials, widget: object, fields: [
              {label: "Link naar Instagram", name: "instagram", widget: "text"},
              {label: "Link naar Facebook", name: "facebook", widget: "text"},
              {label: "Link naar Spotify", name: "spotify", widget: "text"},
              {label: "Mailto link (google dit)", name: "mail", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "First Paragraph", name: "firstText", widget: "text"},
              {label: "Second Paragraph", name: "secondText", widget: "text"},
              {label: "Third Paragraph", name: "thirdText", widget: "text"}]}
          - {label: "Songs", name: songs, widget: object, fields: [
              {label: "First Song", name: "firstSong", widget: "file"},
              {label: "Second Song", name: "secondSong", widget: "file"},
              {label: "Third Song", name: "thirdSong", widget: "file"},
              {label: "Fourth Song", name: "fourthSong", widget: "file"}]}
          - {label: "Footer", name: footer, widget: object, fields: [
              {label: "Footer Image", name: "image", widget: "image"}]}